class Constants {
  CAMPAING_DAYS = {
    Sunday: "Sunday",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
  };

  INTENCAO_MENSAGEM = {
    FAZER_PEDIDO: "FAZER_PEDIDO",
    SAUDACAO_OI: "SAUDACAO_OI",
    SAUDACAO_BOM_DIA: "SAUDACAO_BOM_DIA",
    SAUDACAO_BOA_TARDE: "SAUDACAO_BOM_TARDE",
    SAUDACAO_BOM_DIA: "SAUDACAO_BOM_DIA",
    FAZER_PEDIDO: "FAZER_PEDIDO",
    FAZER_PEDIDO: "FAZER_PEDIDO",
    FAZER_PEDIDO: "FAZER_PEDIDO",
  };

  WHATSAPP_EVENTS = {
    AUTHENTICATED: "authenticated",
    AUTHENTICATION_FAILURE: "authentication_failure",
    READY: "ready",
    CHAT_REMOVED: "chat_removed",
    CHAT_ARCHIVED: "chat_archived",
    MESSAGE_RECEIVED: "message_received",
    MESSAGE_CIPHERTEXT: "message_ciphertext",
    MESSAGE_CREATE: "message_create",
    MESSAGE_REVOKED_EVERYONE: "message_revoked_everyone",
    MESSAGE_REVOKED_ME: "message_revoked_me",
    MESSAGE_ACK: "message_ack",
    MESSAGE_EDIT: "message_edit",
    UNREAD_COUNT: "unread_count",
    MESSAGE_REACTION: "message_reaction",
    MEDIA_UPLOADED: "media_uploaded",
    CONTACT_CHANGED: "contact_changed",
    GROUP_JOIN: "group_join",
    GROUP_LEAVE: "group_leave",
    GROUP_ADMIN_CHANGED: "group_admin_changed",
    GROUP_MEMBERSHIP_REQUEST: "group_membership_request",
    GROUP_UPDATE: "group_update",
    QR_RECEIVED: "qr_received",
    LOADING_SCREEN: "loading_screen",
    DISCONNECTED: "disconnected",
    STATE_CHANGED: "state_changed",
    BATTERY_CHANGED: "battery_changed",
    INCOMING_CALL: "incoming_call",
    REMOTE_SESSION_SAVED: "remote_session_saved",
    VOTE_UPDATE: "vote_update",
  };

  // ABBREVIATED_WORDS = {
  //   qndo: "quando",
  //   pço: "preço",
  //   qnd: "quando",
  //   qtd: "quantidade",
  //   agr: "agora",
  //   td: "tudo",
  //   vc: "você",
  //   vcs: "vocês",
  //   tbm: "também",
  //   tb: "também",
  //   pq: "porque",
  //   ñ: "não",
  //   n: "não",
  //   obg: "obrigado",
  //   kd: "cadê",
  //   cmg: "comigo",
  //   dp: "depois",
  //   blz: "beleza",
  //   hj: "hoje",
  //   fds: "fim de semana",
  //   msm: "mesmo",
  //   vdd: "verdade",
  //   ctz: "certeza",
  //   aq: "aqui",
  //   aki: "aqui",
  //   sdd: "saudade",
  //   qq: "qualquer",
  //   qm: "quem",
  //   bjs: "beijos",
  //   dps: "depois",
  //   mt: "muito",
  //   mto: "muito",
  //   blza: "beleza",
  //   flw: "falou",
  //   abs: "abraços",
  //   blza: "beleza",
  //   kra: "cara",
  //   vamo: "vamos",
  //   vamoa: "vamos",
  //   eh: "é",
  //   d: "de",
  //   ta: "está",
  //   tá: "está",
  //   aki: "aqui",
  //   akiu: "aqui",
  //   tdo: "tudo",
  //   qlq: "qualquer",
  //   vcê: "você",
  //   msg: "mensagem",
  //   msgs: "mensagens",
  //   tc: "teclar",
  //   naum: "não",
  //   ñao: "não",
  //   intao: "então",
  //   xau: "tchau",
  //   brigado: "obrigado",
  //   xat: "chat",
  //   dxa: "deixa",
  //   falo: "falou",
  //   cel: "celular",
  //   dexa: "deixa",
  //   to: "estou",
  //   fofaum: "fofão",
  //   djow: "deixa",
  //   irl: "na vida real",
  //   lol: "risada",
  //   pls: "por favor",
  //   rsrs: "risos",
  //   vlw: "valeu",
  //   flw: "falou",
  //   parabens: "parabéns",
  //   tbz: "também",
  //   bn: "boa noite",
  //   bf: "bom fim de semana",
  //   ehh: "é",
  //   fzer: "fazer",
  //   esq: "esqueci",
  //   prt: "parte",
  //   flwr: "flores",
  // };
}

export default new Constants();
